services:
  fastapi:
    build: .
    container_name: mymathapp2
    ports:
      - "8000:8000"
    volumes:
      - .:/solvemath
    working_dir: /solvemath
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
